export const ChunkSettings = {
	WORLD_CNT: 100,
	ELEMENTS_PER_QUAD: 3,
	BYTES_PER_QUAD_ELEMENT: 4,
	MAX_QUADS_PER_BLOCK: 54,
	SIZE: 16,
	get BYTES_PER_CHUNK_QUADS() { 
		return this.ELEMENTS_PER_QUAD * this.BYTES_PER_QUAD_ELEMENT * this.MAX_QUADS_PER_BLOCK * (this.SIZE ** 3);
	},
	CHUNK_ID_ELEMENTS: 1,
	CHUNK_ID_BYTES_PER_ELEMENT: 4,
	get CHUNK_ID_BYTES() {
		return this.CHUNK_ID_ELEMENTS * this.CHUNK_ID_BYTES_PER_ELEMENT;
	},
	ELEMENTS_PER_UNIFORM: 20,
	BYTES_PER_UNIFORM_ELEMENT: 4,
	get BYTES_PER_UNIFORM() {
		return this.ELEMENTS_PER_UNIFORM * this.BYTES_PER_UNIFORM_ELEMENT;
	},
	ELEMENTS_PER_CHUNK_DATA: 4,
	BYTES_PER_CHUNK_DATA_ELEMENT: 4,
	get BYTES_PER_CHUNK_DATA() {
		return this.ELEMENTS_PER_CHUNK_DATA * this.BYTES_PER_CHUNK_DATA_ELEMENT;
	},
	get BYTES_PER_CHUNK_DATA_BUFFER() {
		return Settings.ACTIVE_CHUNKS * this.BYTES_PER_CHUNK_DATA;
	}
};

export const TransformSettings = {
	COUNT: 1000,
	ELEMENTS_PER_TRANSFORM: 20,
	BYTES_PER_ELEMENT: 4,
	get BYTES_PER_TRANSFORM() {
		return this.ELEMENTS_PER_TRANSFORM * this.BYTES_PER_ELEMENT;
	},
	ELEMENTS_PER_METADATA: 1,
	BYTES_PER_METADATA: 2,
	get BYTES_PER_METADATA() {
		return this.ELEMENTS_PER_METADATA * this.BYTES_PER_METADATA;
	},
	
};

export const BlockSettings = {
	MODEL_SIZE: 16,
	TEXTURE_SIZE: 16,
	DEFAULT_SCALE: [this.MODEL_SIZE, this.MODEL_SIZE, this.MODEL_SIZE],
	DEFAULT_POSITION: [0, 0, 0],
	DEFAULT_ROTATION: [0, 0, 0],
	DEFAULT_PIVOT: [0, 0, 0],
	DEFAULT_INSET: 0,
	DEFAULT_INSET_ANGLE: 0,
	DEFAULT_UV: [0, 0, this.TEXTURE_SIZE, this.TEXTURE_SIZE],
}

export const TextureSettings = {
	TERRAIN_ATLAS_SIZE: [1024, 2048],
	
}